keys:
  - &admin_gaspard age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
  - &server_ovh age15x7zcnpypyr2dj8ma4q3sw8atvlj3txej6gt93p0rhjgmqlvkd6qjd9tsm
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        age:
          - *admin_gaspard
          - *server_ovh
