on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: cachix/cachix-action@v17
        with:
          name: gasdev
      - name: Install omnix
        run: nix profile install nixpkgs#omnix
      - run: om ci
