example_key: ENC[AES256_GCM,data:ItFDpzCo+TWPqHtWdQ==,iv:b72CBu9TDQBJHrvYnyqvXqVwXgUIF4sfvzjYSZ5vua0=,tag:XbEh6j/L8jAt+dmmFh8W+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSDNVR2JWZ3lyaXlKdzRJ
            a3hnbHZhQTZYdTdjdVVwdyt3VEo5OGNvWlFBCnZYUTI3TG9IVVAwclZac0piZEMz
            d0hxTmZ0TUphUlFyd2lzOFhYdjlUVEUKLS0tIEw2WjBPYzA4V0hhWnZ4SHduMU1D
            OUljRlE1ays5MU1ZcnJoZjBmWTJrRkEKk6tZ9U2xk+SvNLMJr/h2PGVmSxjA0wnt
            S6n5DeDldvcQpvlNbaWKGa1DjYyL9NGD2YjaZb+VseyB7L09piOKtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeUpJbDcvT0xhUThaSFZI
            K0dUU2lhMnZaWkJUQlJiN2t6SDdrZVQ3akV3CmZnMWNEZ2pKR3gzaEVhaDQvNWxH
            cXMvdjc2dFNxUnltSEQ5QnZFM1lycEUKLS0tIHlmckh1d3BobERPajlGb0xIQ1ZB
            KzRoaUJnazZBY3Q5NlhkMndqQmQyNDgKm5Rckr+wL3IqNfnromYCYIDsuJRfJNqi
            APHBINqzOwa3d7MkNhq/LfOGA9Flhh12SxnkGlkRGqsSh8djdfJVfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x7zcnpypyr2dj8ma4q3sw8atvlj3txej6gt93p0rhjgmqlvkd6qjd9tsm
    lastmodified: "2026-08-16T12:58:26Z"
    mac: ENC[AES256_GCM,data:lWSdOC4TIiWXjTg+eSAIBwDJ0hgCZ86TPY8EpDTKtIu9Yk8Omlfe9VaQLr9nJz5T6KehcQie+RWTUsIzLVjrsZT5ZWtK3qqqkOpmhWu5DJ6GH3IakXlw98qE8zkZpaDnAnF4Ga1gMh5sFJUmKKF7bWunJKOC4oWKaFDxN6ZfrTU=,iv:IvOzjd9zdrkeHhgRLmpLLZGYLBXjW6fk27BDAh656lU=,tag:lmgjhN0CblkKAR90r/Ilig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
