backend.env: ENC[AES256_GCM,data:dbeHjOasJeLtXYRWANmWMlodcUDDG08l20LAzTj+crP3FSEj6XPHZVvqUjtkiVw6ihydOG48WUjidyJtrb7qvO6ybC6N965MUVEDT/HyRCpqpwghK9+9v6wzRoRExhYJlZVPc/ohONok13g8J1LNAMvmjVGEB1hUC1DIsITsaXLxpJJg8/Iy+8m3Ee89YK8qk9mZQsTztyTjFJKjsm3zGwVz5gTq6QUBnVsJT+XpKJxSnuKkyctdUwg0B/obKXCujhGpkgn4dmRo0tB9HfcFiubL3TDDEzRzx/I64YWz8F803VWB08GsQUOXiqwhFT71pmafr89xMZHx5DPPvCz7YaiqOvBP0nyubHBWfcukoPo9jWKKemuoSrFZHELOaagUwdr9hNMXnrn8SyfFRqX0JQ+eOgDNHoW/rRpxbHuK4Ac1coVtIEwFO0BhLRNLqby7nooshThXnOItirL6tjS/WE6Is5fo1plKWymg9HWhdz1C9nvpnXAWC3k1jvMzZOBjQUYUbkPc2UeFNK1k2cdRgg6793RkevJt3DDbF8OhBGJF6NUoqZjx984hGiKHDJWgNsdayQvERFlio9zsXryWCdp/trs+xjeJSOLu1jilPfbsAvCejhDxaers3ew531TQDv00iLKc1evZgDpnXJ8azbHUSj0J/t0GPHqiSo8rIn5gwkQ+WcvJ9rE9zDdjj97FikpHcjucKl8fHNW4RKPMK82IKhoUPEcjTh6Yjy2Isb970reOz56JV8FHxlfSFfaQ5i67F9Li6ki3ERLemyCJNITL0W2JE12KN58e5Q==,iv:Fm6M+RC/r1WiUt+fjKxhZEiWZZ2hZpWbfiL6VqEoMI8=,tag:+v3W7+5JY2R73IoIMq7z9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSDNVR2JWZ3lyaXlKdzRJ
            a3hnbHZhQTZYdTdjdVVwdyt3VEo5OGNvWlFBCnZYUTI3TG9IVVAwclZac0piZEMz
            d0hxTmZ0TUphUlFyd2lzOFhYdjlUVEUKLS0tIEw2WjBPYzA4V0hhWnZ4SHduMU1D
            OUljRlE1ays5MU1ZcnJoZjBmWTJrRkEKk6tZ9U2xk+SvNLMJr/h2PGVmSxjA0wnt
            S6n5DeDldvcQpvlNbaWKGa1DjYyL9NGD2YjaZb+VseyB7L09piOKtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeUpJbDcvT0xhUThaSFZI
            K0dUU2lhMnZaWkJUQlJiN2t6SDdrZVQ3akV3CmZnMWNEZ2pKR3gzaEVhaDQvNWxH
            cXMvdjc2dFNxUnltSEQ5QnZFM1lycEUKLS0tIHlmckh1d3BobERPajlGb0xIQ1ZB
            KzRoaUJnazZBY3Q5NlhkMndqQmQyNDgKm5Rckr+wL3IqNfnromYCYIDsuJRfJNqi
            APHBINqzOwa3d7MkNhq/LfOGA9Flhh12SxnkGlkRGqsSh8djdfJVfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x7zcnpypyr2dj8ma4q3sw8atvlj3txej6gt93p0rhjgmqlvkd6qjd9tsm
    lastmodified: "2026-08-16T13:41:36Z"
    mac: ENC[AES256_GCM,data:6a+9o70xjew3m6gc3Qph8EMaE1qQm8Vj4+ZybvXV/aF9xt8T6QcfgvCEW77n76EkI+x4frG6AXbdiRoaYcBlN+pjV9FpfvxKSru/CHZPK7CRwq+BOJ+wPqNa2apdSt3nIzPtWxSh1+jl1VqFyM37x0dM2Hd2Jrv3hPoPjuzjrKw=,iv:0cQJCQDm9vX7IR+Al2B1nU4Po3oa8vKjZez/okqDzKk=,tag:qTIDmneg7WBw8ryNdvZLzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
