backend-env: ENC[AES256_GCM,data:YSA4x//H7deG+bkK0wKL+ufH5uFp9K5vAuxWf0tBnI2fQiy88ndQZcYkQvY+zEyDQ87AmZH8YCUx1yRYeyb1QF1q9QezTPKW4kGJKaA96WxHlgG0O0WO7W3NYBsoAk16tNJ+QPiLQuB8dGjXmSqP57IIXhHSqlr5xyE9seb/TS95MzS2aVgt4//E8nplkOIovRkYiv99CoNsTqvx0OY4uHwpaK3Bse6U9ln3C2IplC7R31ca1fh90N/x9E+PqU4+/og7wNNHbIXIeXzmQmrnf5/cNMxZAz6D+nbze/XYEpMRwoInT4HHaY7zyTUHwK7rI6x+raueygA2mVgW07FejEnIXEJHohzyzEXqg1BaRu0YyaFYQP0qsy7D81bjepoDR77nNAEJbx/y3NQBDVorPKiUo2SPzKjO6iLkaT3XnUI375kjWArSkkFnjb+DrFsBuWbjPLZEqmoax1YQjsQz2D5HOLMKNSWYNqN8q7kvWhGGNIKgWSYKwIOYYAmazkcKtxt9droHpS10oOkL6DBdjI9WybQgRD9pwG2z8EhFxbTKDEcxGRocqBA1srYhUlYMU55+1l2vEJ2aekEehzj6jI6Fs0r6i4iNukRjWIDsSvu+fR0L7QGSdFDmEMY48kauj6SQ95brJRvpcONAVu3ZMpHOJLA0vUfppjbKRI3/cK7KPFKQG3pDmq5ByUYhIbFJfv5zsngaZefQO90DSJnDoCwa3Z4k9mY8C+88lIjnlq3VLGtMClytrK32JxAqUaEBchOHd04jO0X26l5EK16ENLT+kX6Q6jOPav809g==,iv:YkK+VFFl7e2QJ50PTIVZBz05PH8YnR+Nf4YIhlpZj5w=,tag:ezW05R3sMRcPDFMCyJLTcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSDNVR2JWZ3lyaXlKdzRJ
            a3hnbHZhQTZYdTdjdVVwdyt3VEo5OGNvWlFBCnZYUTI3TG9IVVAwclZac0piZEMz
            d0hxTmZ0TUphUlFyd2lzOFhYdjlUVEUKLS0tIEw2WjBPYzA4V0hhWnZ4SHduMU1D
            OUljRlE1ays5MU1ZcnJoZjBmWTJrRkEKk6tZ9U2xk+SvNLMJr/h2PGVmSxjA0wnt
            S6n5DeDldvcQpvlNbaWKGa1DjYyL9NGD2YjaZb+VseyB7L09piOKtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeUpJbDcvT0xhUThaSFZI
            K0dUU2lhMnZaWkJUQlJiN2t6SDdrZVQ3akV3CmZnMWNEZ2pKR3gzaEVhaDQvNWxH
            cXMvdjc2dFNxUnltSEQ5QnZFM1lycEUKLS0tIHlmckh1d3BobERPajlGb0xIQ1ZB
            KzRoaUJnazZBY3Q5NlhkMndqQmQyNDgKm5Rckr+wL3IqNfnromYCYIDsuJRfJNqi
            APHBINqzOwa3d7MkNhq/LfOGA9Flhh12SxnkGlkRGqsSh8djdfJVfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x7zcnpypyr2dj8ma4q3sw8atvlj3txej6gt93p0rhjgmqlvkd6qjd9tsm
    lastmodified: "2026-08-16T13:36:10Z"
    mac: ENC[AES256_GCM,data:bw+RFMsrK7vAY/WQq54AMQZskeDmc4zMqjPj5AlH6vvoycjf52sV3jg3SZYWSRjnG476gJhixx6c9EDfmcUby80i7XiYY6cuuHoY6e4/qFO4fwQyk6E+MiBSn2vhtnwt6/UYqIAUdWwBTrOF+182/+/FCgPWSKmCA/D22HkMpiM=,iv:h5Zojn7s7J73dy8Kl1pgnR3rOxI0YmFKjKozPO6iioo=,tag:Cxl6ao4mLwJpR5/Tkvk11A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
